Aqaint 182
etolmachev/BookingSpec pull request #2
Opened 2017-12-20 11:06 UTC by vkrasnobelmov

2017-12-25 06:22 UTC, IgorRukhlenko requested changes

2017-12-25 06:22 UTC, IgorRukhlenko commented on BookingSpecBindings/Bindings/SignInPopUpBindings.cs
> +			Assert.That(signPage.GetErrorText().Contains(message), Is.True);
Contains() is not enough here. It's better to compare an entire message to catch possible issues with text.

2017-12-25 06:22 UTC, IgorRukhlenko commented on BookingSpecTests/LoginFeature.feature
> +﻿Feature: Login
Please fix usage of When and Then in this feature file.

2017-12-25 06:22 UTC, IgorRukhlenko commented on BookingSpecTests/LoginFeature.feature
> +	Then I click button Cancel on Forgot Your Password PopUp
Need to check that Cancel button will lead to the expected system behavior.

2017-12-25 06:22 UTC, IgorRukhlenko commented on BookingSpecTests/LoginFeature.feature
> +Scenario: Check that previous values in PopUp fields are saved
There is no actual check that previous values are saved in this scenario.

2017-12-25 06:22 UTC, IgorRukhlenko commented on BookingSpecTests/LoginFeature.feature
> +Scenario: Check that previous values in PopUp fields are not saved
There is no actual check that previous values are not saved in this scenario.

2017-12-26 06:37 UTC, IgorRukhlenko approved these changes

2017-12-26 10:43 UTC, etolmachev requested changes

2017-12-26 10:43 UTC, etolmachev commented on BookingSpecBindings/Bindings/ForgotYourPasswordPopUpBindings.cs
> +		[Then(@"I wait while page popup is loading")]
Dublicated methods

2017-12-26 10:43 UTC, etolmachev commented on BookingSpecBindings/Bindings/SignInPopUpBindings.cs
> +			Assert.AreEqual(signPage.GetEmailText(), "testmirantistest@gmail.com");
Use parameter for email, store email value in FF

2017-12-26 14:51 UTC, merged