Aqaint 181
etolmachev/BookingSpec pull request #4
Opened 2017-12-25 13:17 UTC by vkrasnobelmov

Registration. Feature file.

2017-12-26 08:33 UTC, IgorRukhlenko requested changes

2017-12-26 08:33 UTC, IgorRukhlenko commented on BookingSpecTests/RegistrationFeature.feature
> +	Then I see that I am Registered and Signed In
Why we cannot use step 'Then I see that I am Signed In ' here?

2017-12-26 08:33 UTC, IgorRukhlenko commented on BookingSpecTests/RegistrationFeature.feature
> +Scenario: Input email and pass that already registered and make sure that I am signed in
Let's rename it to something more simple like: Try to register as already registered user.

2017-12-26 08:33 UTC, IgorRukhlenko commented on BookingSpecTests/RegistrationFeature.feature
> +Scenario: Input email that already registered and invalid pass to make sure that I am not registered and not signed in
Let's make the scenario name more simple and clear.

2017-12-26 08:33 UTC, IgorRukhlenko commented on BookingSpecTests/RegistrationFeature.feature
> +	Then I see that I am not Signed In and not Registered
Not obvious step. Let's split it.

2017-12-26 08:33 UTC, IgorRukhlenko commented on BookingSpecTests/RegistrationFeature.feature
> +	Then I see that credential values are saved in Register PopUp fields
How are you going to check that proper credentials are saved?

2017-12-26 08:33 UTC, IgorRukhlenko commented on BookingSpecTests/RegistrationFeature.feature
> +	Then I see that credential values are not saved in Register PopUp fields
How are you going to check that proper credentials are not saved?

2017-12-26 08:33 UTC, IgorRukhlenko commented on BookingSpecBindings/Bindings/SignInPopUpBindings.cs
> +		[Then(@"I see that credential values are saved in Sign In PopUp fields")]
Such step implementation cannot be used for other users and there is no check that password also saved.

2017-12-26 08:33 UTC, IgorRukhlenko commented on BookingSpecBindings/Bindings/SignInPopUpBindings.cs
> +		[Then(@"I see that credential values are not saved in Sign In PopUp fields")]
There is no check for password field.

2017-12-29 04:42 UTC, IgorRukhlenko approved these changes

2017-12-29 07:50 UTC, etolmachev requested changes

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Bindings/SignInPopUpBindings.cs
> +		[Then(@"I check that I am not Registered")]
Step name doesn't apply to what it does. Check it please

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/TestBase/Pages/RegisterPopUp.cs
> +			string EmailValue = EmailField.GetAttribute("value");
Make it one line method to be consistent

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/TestBase/Pages/RegisterPopUp.cs
> +			string PassValue = PassField.GetAttribute("value");
Make it one line method to be consistent

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/TestBase/Pages/SignInPopUp.cs
>  			string EmailValue = EmailField.GetAttribute("value");
Make it one line method to be consistent

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/TestBase/Pages/SignInPopUp.cs
> +			string PassValue = PassField.GetAttribute("value");
Make it one line method to be consistent

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Utils.cs
> +	class Utils
This class must be static.

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Utils.cs
> +		public static string rnd(string email)
It's better to pass to rnd() only int length. This method should not be responsible for parsing strings.

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Utils.cs
> +		public static string Context(string email)
You should pass key right away, this method is about working with context, not about parsing strings.

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Utils.cs
> +		private static Random random = new Random();
Must be defined in rnd method

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Utils.cs
> +		public static string Resolve(string result)
Rename result to something more suitable.

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Utils.cs
> +			string placeholder = Regex.Match(result, regexLeft).ToString();
Rename placeholder to "methodName"

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Utils.cs
> +			Console.WriteLine(placeholder);
Remove unneeded debug output

2017-12-29 07:50 UTC, etolmachev commented on BookingSpecBindings/Utils.cs
> +					return rnd(result);
It's better for rnd and context methods return only resolved value for {{a::b}}. You should combine final result string in Resolve method.

2017-12-29 10:59 UTC, merged