Accommodation search
etolmachev/BookingSpec pull request #6
Opened 2018-01-23 12:23 UTC by vkrasnobelmov

2018-01-29 14:14 UTC, etolmachev requested changes

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/Bindings/AccomodationSearchResultBindings.cs
> +						Browser.Driver.FindElement(By.CssSelector("a[data-id='oos-1']")).Click();
Need to cover case with scenario context column in the table

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/Bindings/AccomodationSearchResultBindings.cs
> +			Assert.IsTrue(true);
No need in this line. If you got here, it means step is passed

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/Checkbox.cs
> +		private HtmlElement checkboxElement;
It's better to inherit HtmlElement. It already has wrapped element(IWebElement), you can reuse it here

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/TestBase/ExpectedSearch.cs
> +			foreach (var row in table.Rows)
Looks like you will store and compare only last row. For both actual and expected searches you need to have collections. Here you need to put row in the constructor and in the step you need to create collection of ExpectedSearch elements

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/TestBase/ExpectedSearch.cs
> +	public class ExpectedSearch
Better call it ExpectedSearchItem

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/TestBase/Pages/AccommodationSearchResult.cs
> +			category = "Top Picks for " + category;
Make it one line method

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/TestBase/ExpectedSearch.cs
> +						break;
Need to add default case

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/TestBase/Pages/MainPage.cs
> +			Autocomplete = new HtmlElement(By.XPath("//b[contains(text(), '"+desiredDestination+"')]"));
Make it one line method

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/TestBase/Pages/MainPage.cs
> +					break;
Need to add default case

2018-01-29 14:14 UTC, etolmachev commented on BookingSpecBindings/TestBase/Pages/MainPage.cs
> +		Regex reg = new Regex(pattern);
Why you didn't use datetime objects?

2018-01-30 07:43 UTC, vkrasnobelmov commented on BookingSpecBindings/Bindings/AccomodationSearchResultBindings.cs
> +						Browser.Driver.FindElement(By.CssSelector("a[data-id='oos-1']")).Click();
Since results are already shown as available there is no value next to this filter so we dont need scenario context here

2018-02-12 10:54 UTC, merged